---
name: safer-aks-upgrades
trigger:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: cnp-azuredevops-libraries
      type: github
      ref: refs/heads/master
      name: hmcts/cnp-azuredevops-libraries
      endpoint: 'hmcts (1)'

parameters:
  - name: kvConnectedServiceName
    default: 'azurerm-sandbox'
  - name: environment_components
    type: object
    default:
      - deployment:
        environment: sbox
        component: run pluto commands on sbox
        service_connection: dcd-cftapps-sbox
        department: cft
        aks:
          subscription: DCD-CFTAPPS-SBOX
          resource_group: cft-sbox-00-rg
          name: cft-sbox-00-aks

variables:
  - name: timeoutInMinutes
    value: 60
  - name: agentPool
    value: ubuntu-latest
  - template: vars/input-variables.yaml@cnp-azuredevops-libraries

stages:
  - ${{ each deployment in parameters.environment_components }}:
      - stage: ${{ deployment.deployment }}
        dependsOn: ${{ deployment.dependsOn }}
        jobs:
          - job: ${{ deployment.environment }}
            displayName: ${{ deployment.environment }}
            pool:
              vmImage: ${{ variables.agentPool }}
            timeoutInMinutes: ${{ variables.timeoutInMinutes }}
            steps:
              - checkout: self
                persistCredentials: true
                clean: true

              - task: CmdLine@2
                displayName: 'Install Pluto'
                inputs:
                  script: |
                    sudo apt-get update
                    echo Downloading Pluto...
                    wget github.com/FairwindsOps/pluto/releases/download/v5.10.1/pluto_5.10.1_linux_amd64.tar.gz
                    tar xzvf pluto_5.10.1_linux_amd64.tar.gz
                    echo Pluto downloaded successfully!      

              - task: AzureKeyVault@1
                displayName: 'Get GitHub API token from Keyvault'
                inputs:
                  runAsPreJob: false
                  ConnectedServiceName: ${{ parameters.kvConnectedServiceName }}
                  keyVaultName: 'infra-vault-nonprod'
                  secretsFilter: 'github-api-token'

              - task: AzureCLI@2
                displayName: ${{ deployment.environment }} - run pluto commands
                inputs:
                  azureSubscription: ${{ deployment.service_connection }}
                  scriptType: 'bash'
                  scriptPath: 'scripts/run_pluto.sh'
                  arguments: '${{ deployment.aks.subscription }} ${{ deployment.aks.resource_group }} ${{ deployment.aks.name }} ${{ deployment.environment }} ${{ deployment.department }}'

              - pwsh: |
                  Get-ChildItem $(System.DefaultWorkingDirectory) -Recurse
                name: DebugCheckout
                displayName: Debug script checkout

              - powershell: |
                  $plutoOutput = Get-Content "/home/vsts/outputfile.txt"
                  Write-Host "##vso[task.setvariable variable=testvar;]$plutoOutput"
                  name: plutoOutput
                  displayName: Read pluto outputs

              - task: GitHubComment@0
                inputs:
                  gitHubConnection: 'hmcts (1)'
                  repositoryName: 'safer-aks-upgrades'
                  comment: '$(testvar)'